name: CI - Optimized

on:
  pull_request:
    branches: [main, develop]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Nx Cloud setup
        uses: nrwl/nx-set-shas@v4

      - name: Lint all projects
        run: pnpm nx run-many --target=lint --all --parallel=3

      - name: Format check
        run: pnpm nx format:check

      - name: Test all projects
        run: pnpm nx run-many --target=test --all --parallel=3 --configuration=ci

      - name: Build all projects
        run: pnpm nx run-many --target=build --all --parallel=3 --configuration=production
