name: Deploy to Firebase

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js のセットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Rust のセットアップ
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 依存関係のインストール
      - run: npm ci --legacy-peer-deps
      - run: npx cypress install

      # Nx Cloud の設定
      - uses: nrwl/nx-set-shas@v4

      # ビルド
      - run: npx nx run-many --target=build --all

      # Firebase CLI のインストール
      - run: npm install -g firebase-tools

      # Firebase へのデプロイ
      - run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
